os: osx

before_script:
  - brew cask install microsoft-office

script:
  - mkdir Fonts
  - FONT_DIR=$(/Applications/Microsoft\ OneNote.app/Contents/Resources/ | ls -d */ | grep -i "fonts")
  - cp -av /Applications/Microsoft\ OneNote.app/Contents/Resources/${FONT_DIR}/* ./Fonts/
  - cp -av /Applications/Microsoft\ Word.app/Contents/Resources/${FONT_DIR}/* ./Fonts/

after_script:
  - cd Fonts
  - git init
  - git config user.name "SomeBlu"
  - git config user.email "webmaster@someblu.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/someblu/Microsoft-Fonts
    - secure: Rsi+G4mkHHKFe6qp19MNuWKHdKqZz6stLYotSlIXqt/xz7h5xqQU4JJrTwugvIskwQxWI0AxeY4HG5yLlbLCYJ2YrnzI06ex8rbpkmT8IZ/YAEVVCoa//DSw8x7Usr9xNYnpwyUXGGmaVZhOi4Nx2razYOhenCcUB9VZvl3koReh/IjKyGJ5XER8He3i5ONpHMKB4iOxkHFYfLpedcUgLs+cDWK6Aiz8M0TJPjBQPnhaxtk2jyyCEbMdoV1EXCWbC1kp7GqqADLuJAc/57KTZktpv/TsrYN8SOo9V47x3fcY08ENyZwB2Fcyn/P+IiV+FF1J6286aZds29Umk6pbNjot37b6MQTRh6olk/azwDMzuliG9ZT1c+Rn0/vCZgrgQHV9cixcgK1g1ArMR3eNuTq/vsnw329+nY9oRkKgvc7TJiJuiaRYX23DI00YASU98hDpU7hAiy7Ab9Twa9wYuGYk8opSLiwz2nHte0u+sxNSLBD7L7A+z0rxdTEq/uBXd5A+TxtWVEiAPNx4bSxdjhqEkJtQBKxHGQoEAj6/WlWNypdNPEY/FbkRpSNdZYZLRow78GM5Y1SHxNlREDSgZGZUT2Dh3SuJrAwm/WWJk4dwxemJG+PpFSL0pDKIvAZnpTKhJmCqaHteN1IH23KN/OwBjFWq5uLzC2Q4mFaTgJg=

notifications:
  email:
    - webmaster@someblu.com
  on_success: change
  on_failure: always
