os: osx

before_script:
  - file=$(curl -fsSL "https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/microsoft-office.rb")
  - version=$(echo "$file" | grep version | head -1 | perl -ne 'print if s/ +version +'\''(.+)'\''/${1}/')
  - url=$(eval "echo $(echo "$file" | grep url | perl -pe 's/#/\$/' | perl -ne 'print if s/ +url +"(.+)"/${1}/')")
  - curl -fsSL $url -o installer.pkg

script:
  - pkgutil --expand-full installer.pkg tmp
  - mv tmp/Office_fonts.pkg/Payload/DFonts Fonts

after_script:
  - cd Fonts
  - git init
  - git config user.name "SomeBlu"
  - git config user.email "zhoujiahao@bytedance.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/someblu/Microsoft-Fonts

notifications:
  email:
    - zhoujiahao@bytedance.com
  on_success: change
  on_failure: always
